# This will run on Travis' 'new' container-based infrastructure
dist: trusty
sudo: false

branches:
  only:
    - master
    - testing-travis

language: php
php:
  - 5.6

# Environment variables
env:
  global:
    - GH_REPO_NAME: TelegramBotPHP
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/Eleirbag89/TelegramBotPHP.git

# Install dependencies
addons:
  apt:
    packages:
      - if [ "${TRAVIS_PULL_REQUEST}" = "false" -a $TRAVIS_BRANCH = 'master']; then doxygen fi
      - if [ "${TRAVIS_PULL_REQUEST}" = "false" -a $TRAVIS_BRANCH = 'master']; then doxygen-doc fi
      - if [ "${TRAVIS_PULL_REQUEST}" = "false" -a $TRAVIS_BRANCH = 'master']; then doxygen-latex fi
      - if [ "${TRAVIS_PULL_REQUEST}" = "false" -a $TRAVIS_BRANCH = 'master']; then doxygen-gui fi
      - if [ "${TRAVIS_PULL_REQUEST}" = "false" -a $TRAVIS_BRANCH = 'master']; then graphviz fi

# Build your code e.g. by calling make
script:
  - composer require --dev phpunit/phpunit ^5.1
  - phpunit
  - echo "Setup done"

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" -a $TRAVIS_BRANCH = 'master']; ./generateDocumentationAndDeploy.sh fi
