# This will run on Travis' 'new' container-based infrastructure
dist: trusty
sudo: false

branches:
  only:
    - testing-travis

language: php
php:
  - 5.6

# Environment variables
env:
  global:
    - GH_REPO_NAME: TelegramBotPHP
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/Eleirbag89/TelegramBotPHP.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - composer require --dev phpunit/phpunit ^5.1
  - echo "Setup done"

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  #- ./generateDocumentationAndDeploy.sh
